# -*- coding: utf-8 -*-
"""Grip Internship

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qxnHF2WyOddm1vCfD7vGGZa-CQRcbBrF
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Data= pd.read_csv("/GripInternship.csv")

Data

Data.plot(x='Hours',y="Scores", style='o')   
plt.title('Score prediction using ML')    
plt.xlabel('Hours Studied')    
plt.ylabel('Score')    
plt.show()

X = Data.iloc[:, :-1].values    
y = Data.iloc[:, 1].values

from sklearn.model_selection import train_test_split    
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression    
regressor = LinearRegression()    
regressor.fit(X_train, y_train)   
print("Done")

line = regressor.coef_*X+regressor.intercept_  
plt.scatter(X, y)  
plt.plot(X, line);  
plt.show()

print(X_test)   
y_pred = regressor.predict(X_test)

df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})    
df

hours = [[9.25]]  
own_pred = regressor.predict(hours)  
print("Hours Studied = {}".format(hours))  
print("Score predicted = {}".format(own_pred[0]))